name: Review Pull Request
on:
  pull_request:
    types: [opened]

jobs:
  review-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Review Code with AI
      id: review_code
      run: |
        echo "Reviewing code from pull request"
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        CODE=$(cat $(find . -name '*.txt'))
        RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/completions" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "text-davinci-003",
            "prompt": "Review the following code:\n\n$CODE",
            "max_tokens": 500
          }')
        echo "$RESPONSE" | jq -r '.choices[0].text' > review_comments.txt

    - name: Comment on Pull Request
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          AI Code Review Comments:
          ${{ steps.review_code.outputs.review_comments }}
